---

- name: Converge
  hosts: all
  become: True
  become_method: sudo

  tasks:

    - name: "default >>> converge | Include zabbix_agent role to install agent v2"
      ansible.builtin.include_role:
        name: alexanderbazhenoff.linux.zabbix_agent
      vars:
        zabbix_servers_passive: 127.0.0.1
        zabbix_servers_active: 127.0.0.1:10051
        agent_version: 5.0
