namespace: alexanderbazhenoff
name: linux
version: 1.0.5
readme: README.md
authors:
- Aleksandr Bazhenov <>
description: Various roles for Linux
license:
- MIT-0
tags:
  - linux
  - monitoring
  - containers
  - backup
dependencies:
  "community.general": "*"
repository: https://github.com/alexanderbazhenoff/ansible-collection-linux
documentation: https://github.com/alexanderbazhenoff/ansible-collection-linux/wiki
homepage: https://galaxy.ansible.com/alexanderbazhenoff/ansible-collection-linux
issues: https://github.com/alexanderbazhenoff/ansible-collection-linux/issues
build_ignore: []
