---

- name: Converge
  hosts: all
  become: True
  become_method: sudo

  tasks:

    - name: "kvm >>> converge | Include variable(s) for testing"
      ansible.builtin.include_vars:
        file: defaults/main.yml

    - name: "kvm >>> converge | Include lxc role"
      ansible.builtin.include_role:
        name: alexanderbazhenoff.linux.lxcfs
