---

bareos_packages:
  fd:
    - bareos-filedaemon
  sd:
    - bareos-storage
  dir:
    - bareos
    - bareos-storage
    - bareos-filedaemon
    - "{% if use_postgresql %}bareos-database-postgresql{% else %}bareos{% endif %}"
    - bareos-database-tools
    - bareos-bconsole
  webui:
    - bareos-webui
  dir_webui:
    - bareos
    - bareos-storage
    - bareos-filedaemon
    - bareos-webui
    - "{% if use_postgresql %}bareos-database-postgresql{% else %}bareos{% endif %}"
    - bareos-database-tools
    - bareos-bconsole

bareos_path:
  fd:
    - /etc/bareos/bareos-fd.d
    - "{% if ('bareos-traymonitor' in install_additional_bareos_packages) %}/etc/bareos/tray-monitor.d{% else -%}
      /etc/bareos/bareos-fd.d{% endif %}"
    - "/etc/{% if (ansible_os_family == 'RedHat') %}yum.repos.d/bareos.repo{% endif -%}
      {% if (ansible_os_family == 'Debian') %}apt/sources.list.d/bareos.list{% endif %}"
  sd:
    - /etc/bareos/bareos-sd.d
    - "{% if ('bareos-traymonitor' in install_additional_bareos_packages) %}/etc/bareos/tray-monitor.d{% else -%}
      /etc/bareos/bareos-sd.d{% endif %}"
    - "{% if (cleanup_storage_files) %}/var/lib/bareos{% else %}/etc/bareos/bareos-sd.d{% endif %}"
    - "/etc/{% if (ansible_os_family == 'RedHat') %}yum.repos.d/bareos.repo{% endif -%}
      {% if (ansible_os_family == 'Debian') %}apt/sources.list.d/bareos.list{% endif %}"
  dir:
    - /etc/bareos/bareos-dir.d
    - /etc/bareos/bareos-dir-export
    - /etc/bareos/bareos-sd.d
    - "{% if ('bareos-traymonitor' in install_additional_bareos_packages) %}/etc/bareos/tray-monitor.d{% else -%}
      /etc/bareos/bareos-sd.d{% endif %}"
    - /etc/bareos/bareos-fd.d
    - "{% if (cleanup_storage_files) %}/var/lib/bareos{% else %}/etc/bareos/bareos-sd.d{% endif %}"
    - "/etc/{% if (ansible_os_family == 'RedHat') %}yum.repos.d/bareos.repo{% endif -%}
      {% if (ansible_os_family == 'Debian') %}apt/sources.list.d/bareos.list{% endif %}"
    - /etc/bareos/bconsole.conf
  webui:
    - /etc/bareos-webui
    - "/etc/{% if (ansible_os_family == 'RedHat') %}yum.repos.d/bareos.repo{% endif -%}
      {% if (ansible_os_family == 'Debian') %}apt/sources.list.d/bareos.list{% endif %}"
  dir_webui:
    - /etc/bareos/bareos-dir.d
    - /etc/bareos/bareos-dir-export
    - /etc/bareos-webui
    - /etc/bareos/bareos-sd.d
    - "{% if ('bareos-traymonitor' in install_additional_bareos_packages) %}/etc/bareos/tray-monitor.d{% else -%}
      /etc/bareos/bareos-sd.d{% endif %}"
    - /etc/bareos/bareos-fd.d
    - "{% if (cleanup_storage_files) %}/var/lib/bareos{% else %}/etc/bareos/bareos-sd.d{% endif %}"
    - "/etc/{% if (ansible_os_family == 'RedHat') %}yum.repos.d/bareos.repo{% endif -%}
      {% if (ansible_os_family == 'Debian') %}apt/sources.list.d/bareos.list{% endif %}"
    - /etc/bareos/bconsole.conf

bareos_daemons:
  fd:
    - bareos-fd
  sd:
    - bareos-sd
  dir:
    - bareos-sd
    - bareos-fd
    - bareos-dir
  webui:
    - "{% if (ansible_os_family == 'RedHat') %}httpd{% elif (ansible_os_family == 'Debian') %}apache2{% endif %}"
  dir_webui:
    - bareos-sd
    - bareos-fd
    - bareos-dir
    - "{% if (ansible_os_family == 'RedHat') %}httpd{% elif (ansible_os_family == 'Debian') %}apache2{% endif %}"

bareos_ports:
  fd:
    - 9102
  sd:
    - 9103
  dir:
    - 9103
    - 9102
    - 9101
  webui:
    - 9103
    - 9101
    - 80
  dir_webui:
    - 9103
    - 9102
    - 9101
    - 80

postgresql_packages:
  debian_psycopg2:
    - "postgresql{{ '-' ~ postgresql_version | default('') }}"
    - "python{{ (ansible_python.version.major == 3) | ternary('3', '') }}-psycopg2"
  debian:
    - "postgresql{{ '-' ~ postgresql_version | default('') }}"
  redhat_psycopg2:
    - epel-release
    - "postgresql{{ postgresql_version | default('') }}-server"
    - "python{{ ansible_python.version.major }}-psycopg2"
  redhat:
    - epel-release
    - "postgresql{{ postgresql_version | default('') }}-server"
