---

- name: "install dnf | Install packages"   # noqa package-latest
  ansible.builtin.dnf:
    name: "{{ item.package | default('') }}"
    state: latest
    update_cache: True
    disable_gpg_check: "{{ item.disable_gpg_check | default(False) }}"
  register: install_yum_results
  until: install_yum_results is succeeded
  retries: 5
  delay: 5
  when: item.package | length > 0
  with_items:
    - "{{ packages_to_install }}"