---

- name: "install lxc(fs) for centos7 | Install LXC repo"
  ansible.builtin.copy:
    dest: "/etc/yum.repos.d/lxc3.0.repo"
    content: |
      [thm-lxc3.0]
      name=Copr repo for lxc3.0 owned by thm
      baseurl=https://copr-be.cloud.fedoraproject.org/results/thm/lxc3.0/epel-7-$basearch/
      type=rpm-md
      skip_if_unavailable=True
      gpgcheck=1
      gpgkey=https://copr-be.cloud.fedoraproject.org/results/thm/lxc3.0/pubkey.gpg
      repo_gpgcheck=0
      enabled=1
      enabled_metadata=1
    mode: 0644
    owner: root
    group: root