---

- name: "configure lxc net | Set lxc-net file path for CentOS"
  ansible.builtin.set_fact:
    lxc_net_file_path: /etc/sysconfig/lxc-net
  when: ansible_distribution == "CentOS"

- name: "configure lxc net | Set lxc-net file path for Ubuntu"
  ansible.builtin.set_fact:
    lxc_net_file_path: /etc/default/lxc-net
  when: ansible_distribution == "Ubuntu"

- name: "configure lxc net | Check lxc-net config file exists"
  ansible.builtin.stat:
    path: "{{ lxc_net_file_path }}"
  register: lxc_net_filename

- name: "configure lxc net | Change lxc-net config"
  ansible.builtin.lineinfile:
    path: "{{ lxc_net_file_path }}"
    regexp: "{{ item.var }}="
    line: "{{ item.var }}={{ item.value }}"
    state: present
    create: True
    mode: 0644
    owner: root
    group: root
  with_items:
    - { var: 'LXC_BRIDGE', value: '"{{ lxc_default_net_bridge | default(lxcbr0) }}"'}
    - { var: 'LXC_ADDR', value: '"{{ lxc_default_net_addr | default("10.0.3.1") }}"'}
    - { var: 'LXC_NETMASK', value: '"{{ lxc_default_net_netmask | default("255.255.255.0") }}"'}
    - { var: 'LXC_NETWORK', value: '"{{ lxc_default_net_network | default("10.0.3.0/24") }}"'}
    - { var: 'LXC_DHCP_RANGE', value: '"{{ lxc_default_net_dhcp_range | default("10.0.3.2,10.0.3.254") }}"'}
    - { var: 'LXC_DHCP_MAX', value: '"{{ lxc_default_net_dhcp_max | default("253") }}"'}
    - { var: 'USE_LXC_BRIDGE', value: '"{{ use_lxc_default_net | lower }}"' }