---

- name: "enable daemons | enable and start lxc"
  ansible.builtin.systemd:
    name: lxc
    state: started
    enabled: True

- name: "enable daemons | enable and start lxcfs"
  ansible.builtin.systemd:
    name: lxcfs
    state: started
    enabled: True
  when: lxc_technology == "lxcfs"