---

- name: "verifications >>> check daemon | Get active status of the daemon"  # noqa command-instead-of-module
  ansible.builtin.command: systemctl is-active {{ lxc_technology }}
  register: daemon_is_active_results
  until: daemon_is_active_results.stdout == 'active'
  delay: 3
  retries: 20
  ignore_errors: True
  changed_when: False

- name: "verifications >>> check daemon | Get enabled status of the daemon"   # noqa command-instead-of-module
  ansible.builtin.command: systemctl is-enabled {{ lxc_technology }}
  register: daemon_is_enabled_results
  ignore_errors: True
  changed_when: False

- name: "verifications >>> check daemon | Assert that {{ lxc_technology }} is enabled and active"
  ansible.builtin.assert:
    that:
      - daemon_is_active_results.stdout == 'active'
      - daemon_is_enabled_results.stdout == 'enabled'
    fail_msg: |
      Error. {{ lxc_technology }} states: {{ daemon_is_enabled_results.stdout }} /
      {{ daemon_is_active_results.stdout }}
