---

- name: "purge bareos redhat | Cleanup Bareos packages depending on components to install selection"
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
    autoremove: True
  with_items:
    - "{{ bareos_packages | json_query(bareos_components) + install_additional_bareos_packages }}"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int <= 7