---

- name: Prepare
  hosts: all
  gather_facts: True
  become: True
  become_method: sudo

  tasks:

    - name: "default >>> prepare | Install epel_repo (CentOS)"
      ansible.builtin.yum:
        name: epel-release
      when: ansible_distribution == "CentOS"

    - name: "default >>> prepare | Update yum cache (CentOS)"
      ansible.builtin.yum:
        update_cache: True
      when: ansible_distribution == "CentOS"

    - name: "default >>> prepare | Update apt cache (Ubuntu)"
      ansible.builtin.apt:
        update_cache: True
      when: ansible_distribution == "Ubuntu"
