---

- name: "delete zabbix agent | Remove zabbix packages apt (Debian family)"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    autoremove: True
    purge: True
  with_items:
    - zabbix-agent
    - zabbix-agent2
    - zabbix-release
  when: ansible_os_family == "Debian"

- name: "delete zabbix agent | Remove zabbix packages yum (RedHat 7 or lower)"
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
    autoremove: True
  with_items:
    - zabbix-agent
    - zabbix-agent2
    - zabbix-release
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int <= 7

- name: "delete zabbix agent | Remove zabbix packages pacman (ArchLinux)"
  community.general.pacman:
    name: "{{ item }}"
    state: absent
    force: True
    remove_nosave: True
  with_items:
    - zabbix-agent
    - zabbix-agent2
  when: ansible_os_family == "Archlinux"

- name: "delete zabbix agent | Clean-up all zabbix directories and files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/zabbix
    - /usr/share/zabbix
    - /var/lib/zabbix
    - /var/log/zabbix
    - /etc/default/zabbix-agent
    - /usr/sbin/zabbix_agentd
    - /tmp/zabbix-release.deb
    - /tmp/zabbix_agent.html
    - /usr/bin/zabbix_agent2
    - /usr/bin/zabbix_agent
    - /usr/lib/systemd/system/zabbix-agent2.service
    - /usr/lib/systemd/system/zabbix-agent.service
    - /usr/share/man/man8/zabbix_agent2.8.gz
    - /usr/share/man/man8/zabbix_agent.8.gz
  when: zabbix_agent_conf_incl_dir_clean