---

# agent version here:
agent_version: 5.0

# install zabbix-agent2 when possible:
install_v2_agent: True

# customize agent for automatic services discovery and templates add:
customize_agent: True

# delete all agents and config before install:
clean_install: True

# force install zabbix-agent v1:
force_install_agent_v1: False

# lots of debug outputs:
debug_mode: True

# force cleanup zabbix agent directories and files (just to avoid installation/uninstallation scripts bugs):
zabbix_agent_conf_incl_dir_clean: True

# only customzie and configure already installed zabbix agent:
customize_agent_only: False

# Validate certs when downloading packages (to avoid failure on some outdated virtual machines snapshots):
repo_dl_validate_certs: False

# parameters for zabbix agent settings
zabbix_agent_conf_name: zabbix_agentd
zabbix_agent_daemon_name: zabbix-agent
zabbix_agent_binary: zabbix-agent
remote_cmd_key: EnableRemoteCommands
remote_cmd_value: 1
logfile_size_key: LogFileSize
logfile_size_value: 100
zabbix_servers_passive: 10.10.1.2,10.10.1.3
zabbix_servers_active: 10.10.11.2:10051,10.10.1.3:10051
zabbix_host_metadata: Linux


### services discovery parameters for templates add:

# binaries hashes:
binaries_tag_hashes:
  - name: java
    hash: jv
  - name: openvpn
    hash: ovd

# daemon hashes:
daemon_tag_hashes:
  - name: cloudstack-agent
    tag: csa                           # dd637361
  - name: cloudstack-management
    tag: csm                           # dd63736d
  - name: openvpn
    tag: ovd                           # dd6f7664
  - name: mysql
    tag: mql                           # dd6d716c
  - name: mariadb
    tag: mql                           # dd6d716c
  - name: postgresql
    tag: pql                           # dd70716c
  - name: bareos-dir
    tag: brdr                          # dd62726472
  - name: bareos-fd
    tag: brfd                          # dd62726664
  - name: bareos-sd
    tag: brsd                          # dd62727364
  - name: memcached
    tag: mmcchd                        # dd6d6d63636864
  - name: nginx
    tag: ngx                           # dd6e6778
  - name: php-fpm
    tag: pfpm                          # dd7066706d
  - name: httpd
    tag: apch                          # dd61706368
  - name: named
    tag: ndns                          # dd6e646e73
  - name: isc-dhcp-server
    tag: iscdhcp                       # dd69736364686370
  - name: dnsmasq
    tag: dnsm                          # dd646e736d
  - name: fail2ban
    tag: fbn                           # dd66626e
  - name: vsftpd
    tag: vsftp                         # dd7673667470
  - name: gitlab-runner
    tag: gtrn                          # dd6774726e
  - name: nfs-server
    tag: nfs                           # dd6e6673
  - name: zabbix-agent
    tag: zba1                          # dd7a626131
  - name: zabbix-agent2
    tag: zba2                          # dd7a626132
