---

# Containers technology: lxc or lxcfs
lxc_technology: lxc

# Disable if you want to connect with host bridge, pass-through, etc..
use_lxc_default_net: True

# Check host is ready for lxc usage
check_host_is_lxc_ready: True

# Lines to append to default lxc config
append_default_lxc_config: |
  lxc.net.0.type = veth
  lxc.net.0.name = eth0
  lxc.net.0.flags = up
  lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx
  lxc.net.0.veth.pair = pair-lxc
  lxc.start.auto = 1
  lxc.start.delay = 8