galaxy_info:
  role_name: bareos
  namespace: alexanderbazhenoff
  author: Aleksandr Bazhenov
  description: Install and configure Bareos and third-party components.
  license: MIT-0
  min_ansible_version: 2.9.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - buster
        - stretch
        - jessie
    - name: rhel
      versions:
        - 7
  galaxy_tags:
    - bareos
    - linux
    - backup
    - infrastructure
    - services
dependencies: []
