---

dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
driver:
  name: docker
platforms:

  - name: debian10-instance
    image: jrei/systemd-debian:10
    dockerfile: dockerfile_debian.j2
    buildargs:
      image_platform: jrei/systemd-debian
      image_tag: 10
    pre_build_image: False
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: debian11-instance
    image: jrei/systemd-debian:11
    dockerfile: dockerfile_debian.j2
    buildargs:
      image_platform: jrei/systemd-debian
      image_tag: 11
    pre_build_image: False
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: ubuntu1804-instance
    image: jrei/systemd-ubuntu:18.04
    dockerfile: dockerfile_debian.j2
    buildargs:
      image_platform: jrei/systemd-ubuntu
      image_tag: 18.04
    pre_build_image: False
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: ubuntu2004-instance
    image: jrei/systemd-ubuntu:20.04
    dockerfile: dockerfile_debian.j2
    buildargs:
      image_platform: jrei/systemd-ubuntu
      image_tag: 20.04
    pre_build_image: False
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: centos7-instance
    image: centos:centos7
    dockerfile: dockerfile_redhat.j2
    buildargs:
      image_platform: centos
      image_tag: centos7
    pre_build_image: False
    privileged: True
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

scenario:
  test_sequence:
    - dependency
    - lint
    - destroy
    - syntax
    - create
    - converge
    - side_effect
    - verify
    - destroy
provisioner:
  name: ansible
  env:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
lint: |
    export ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/..
    export PY_COLORS=1
    export ANSIBLE_FORCE_COLOR=1
    yamllint .
    ansible-lint .
    flake8 .
verifier:
  name: ansible
